export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCTS_FAILED = 'SET_PRODUCTS_FAILED'


export const AUTHENTICATION_START='AUTHENTICATION_START'
export const AUTHENTICATION_SUCCESS='AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAIL='AUTHENTICATION_FAIL'
export const AUTHENTICATION_LOGOUT='AUTHENTICATION_LOGOUT'
export const AUTHENTICATION_REDIRECTPATH='AUTHENTICATION_REDIRECTPATH'
export const AUTHENTICATION_INITIATE_LOGOUT='AUTHENTICATION_INITIATE_LOGOUT'
export const AUTHENTICATION_CHECK_TIMEOUT='AUTHENTICATION_CHECK_TIMEOUT'

